replicaCount: 1

priorityClassName: stage-low-priority-client-workload

image:
  repository: hub.adm.selectel.org/rehau/map-frontend-admin/map-frontend-admin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "stage"

imagePullSecrets:
  - name: registry-hub-adm-selectel-org

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "adm-dev.maps.rehau.ru"
      paths:
        - "/"
  tls:
    - secretName: tls-dev-maps-rehau-ru
      hosts:
        - "adm-dev.maps.rehau.ru"
